### ISSUE TITLE
Falling through moving platform on Prize for the Reckless

### ISSUE THREAD

**Issue by rensenware** [TerryCavanagh/VVVVVV#543] opened 2020-11-11 16:58 UTC
Title. I've tried getting help with this in the v6cord and nobody else can seem to reproduce my issue. I compiled the game with cmake on Arch Linux, game runs fine, no errors at all, but no matter what options I change / if I have 60 or 30fps on I will always fall through the moving platform leading to the trinket on prize for the reckless. It doesn't matter what direction it moves, if it's touching the wall at the time I get on the platform, I will always phase right through it, making 100% completion impossible. It's compiled from the latest commit.

**Comment by flibitijibibo** [comment] 2020-11-11 17:01
Probably related to #503, #509, #529.

**Comment by AllyTally** [comment] 2020-11-11 22:52
Could you do a `git bisect`?

**Comment by InfoTeddy** [comment] 2020-11-11 23:22
Here is the VVVVVV binary they sent me in DMs - note that, for whatever reason, it directly links with libibus, so it won't launch unless you have that library installed. I have ran it and managed to not reproduce this bug.

* [VVVVVV.zip](https://github.com/TerryCavanagh/VVVVVV/files/5527317/VVVVVV.zip)

On a side note, I would expect something like this to affect conveyors too, and make them no longer move the player. The fact that Rensen has also not reported this happening seems to be a bit strange to me.

So I have a feeling that you must trigger a particular chain of events in order to phase through the Prize for the Reckless platform. So I'll ask this: if you quicksave at the Prize for the Reckless checkpoint, then close the game, then re-launch it, then load the quicksave, then do Prize for the Reckless and free the moving platform by destroying the disappearing platform blocking it, do you phase through the platform after *that*?

Otherwise, as it stands right now, this bug has incomplete information.

**Comment by rensenware** [comment] 2020-11-12 16:05
Yes. It still does that If I load a quicksave.

**Comment by rensenware** [comment] 2020-11-12 16:07
Ah, I discovered that I only fall through the platform if I kill myself while the moving platform is in the gap it passes through once you remove the platform that blocks it.

**Comment by InfoTeddy** [comment] 2020-11-12 20:14
There we go, that was the missing bit of information that you failed to provide previously. Now the bug is 100% reproducible.

I had the same communication fail with the reporter of #391, where I couldn't reproduce the bug until she told me that you have to move left. Everyone in the future should make sure to include *everything* they do to get a bug to happen! Everything! I *cannot* stress this enough! Until you provide everything, we're just banging our heads on the wall (metaphorically speaking).

With this bug reproducible, I can now confirm that this is a regression in 2.3, as this didn't happen in 2.2.

**Comment by flibitijibibo** [comment] 2020-11-12 20:40
>Ah, I discovered that I only fall through the platform if I kill myself while the moving platform is in the gap it passes through once you remove the platform that blocks it.

Ah, game development.

Thanks for digging into this, will keep this marked as a 2.3 blocker.

**Comment by InfoTeddy** [comment] 2020-11-12 21:53
`git bisect` says this bug was caused by 99297659ee9387b0e40d23db44e9b16dc5715113 ("Restore platform evaluation order to 2.2").

This isn't too surprising. The platform collision system is a kludge-filled mess (a platform entity doesn't have an assigned block, instead it magically gets assigned a block ad-hoc every frame based on it and the block sharing the same top-left corner), and as a result, Prize for the Reckless is kludge-filled even more. Instead of fixing the system so disappearing platforms block moving platforms, it and Driller just use a special platform type that will only start moving if the adjacent disappearing platform is touched and removed, which isn't the same thing as a proper fix at all. And this leads to further problems (more on this later).

I think this was caused by 2.2's system unconditionally creating a block every time a platform gets moved, and not caring about what happened to the old block. This is fine, except for when the old block doesn't get taken care of and causes problems (#194). 

And in this case, what's happening here is some kludge failing, which was added to fix some other kludge. As I said two paragraphs ago, Prize for the Reckless and Driller use a special platform type that only starts moving when its adjacent disappearing platform disappears, which is kludge instead of fixing the platform collision system.

But this kludge by itself causes some more issues. When the moving platform starts moving, it never stops. So if you die before the moving platform completely clears the space of the disappearing platform, the disappearing platform will reappear and the moving platform will pass through the disappearing platform, which looks bad. And equally bad, even if the moving platform is clear of the space of the disappearing platform when you die, it will still go back through it after you respawn.

So to fix this, more kludge is added on top of this kludge, where there's a hardcoded routine that teleports the platform across the space of the disappearing platform. And `map.settile()` is called to place an invisible tile on the rightmost tile of the disappearing platform, so that it appears as if the disappearing platform has collision and the moving platform bounces off of it, when in reality it doesn't actually collide with the moving platform at all.

On a sidenote, you can tell the original dev who wrote this kludge (Terry, probably) thought that the tile would show up immediately, so it simply had to be a tile with no texture (tile 59 in `tiles.png`), but in reality it wouldn't show up at all in the first place because of the `graphics.foregrounddrawn` caching system that only ever draws the tiles of the room once.

And like I said, this kludge on top of kludge causes further problems. The room coordinate check guarding the tile placement was written wrongly (the original dev who wrote it, again probably Terry, didn't appear to be familiar with De Morgan's laws - when negating a conditional, you negate its conjunctions ("and" and "or"), too!), so it also applied in other rooms like Boldly To Go, and it applied in custom levels when it shouldn't have (#136). And this platform teleporting thing also happened in custom levels, when it shouldn't have (#144).

So now, the platform teleportation kludge that was added to fix some kludge that was added to fix some kludge, is broken again. The reason being that ever since #503, the game never unconditionally creates a new block whenever it moves a platform, and it has to update a block in-place; otherwise, the platform evaluation order would change around. This works in 99% of cases, except for the case of this kludge, because the platform gets suddenly teleported while its block doesn't get updated accordingly.

Fixing this should be pretty easy; I'll open a PR in a bit.

**Closed** 2020-11-12 22:06 UTC
Labels: required for 2.3
