### ISSUE TITLE
If you mess with your controller bindings on steam deck, you can lock yourself out of being able to do anything

### ISSUE THREAD

**Issue by TerryCavanagh** [TerryCavanagh/VVVVVV#1152] opened 2024-02-10 18:12 UTC
Got a bug report about this via email:

>I have played VVVVVV on a couple consoles over the course of the last few years and recently decided to replay it on my newly acquired Steam Deck.
>
>A while ago I was messing around the menu and activated one of the bind options on the Game Pad menu out of curiosity and now I cannot reset the controls to their original setup. Is there a way to do it?
>
>I have, of course, looked up for answers on the internet and there seemed to be none for this particular problem on the Steam Deck (most of them require manipulating save files directly as in PC versions, for example).
>
>I am not so sure of how clear I have been on the issue, but the Reddit post below deals with the exact same topic and illustrates it better than I have done. Anyway, any option makes it clunky to play the game and hinders my enjoyment. It would be great to reset it or to add an option to do it.
>
>https://www.reddit.com/r/VVVVVV/comments/11rrvib/uhhelp_how_do_i_reset_controller_keybinds_cant/

(I haven't tried this myself, so I don't fully understand what the problem is)

**Comment by Daaaav** [comment] 2024-02-10 18:41
Some safeguards were added in 2.4 preventing you from getting locked out, it's still not ideal but the worst problems with the menu have been fixed. Worst case, if you locked your keys in the car (by removing all binds from the flip/confirm button and then exiting the menu), restarting the game should fix that.

In 2.3 it used to be really bad - every button you set to the "menu" (esc) binding would get stuck there without an opportunity to rebind them to something else anymore (like flip/confirm...) but that's now fixed. Now the menu works as designed, but many people seem to not understand the design, even though I think alternative designs would be clumsier... Especially if you want to swap around A and B, and you have to use whatever the _current_ "confirm" button is to bind anything.

The input system will get an overhaul for action sets anyway, maybe in the meantime we can think of some possible designs that are easier to use (especially since non-steam users will still get an in-game binding menu). And a reset button would be nice.

Maybe we could also display button labels in the menu, console style? Like there's a `(A) Confirm (B) Back` in the corner?

**Comment by TerryCavanagh** [comment] 2024-02-12 13:48
Thanks, this is a good overview of the state of things! Good to know that we have a solution for locking the keys in the car, in particular :)

> Maybe we could also display button labels in the menu, console style? Like there's a (A) Confirm (B) Back in the corner?

I think this is a good idea! (but it can probably wait until 2.5).

For 2.4.1, I think all we need to address this is some kind of reset keybind action that you can do with a controller. It can just be a trouble shooting thing for situations like this for now.

Here's a suggestion, feedback welcome: on a steam deck, you have access to the following key using the steam button:

> Steam Button + Down on D-Pad - Tab Key

If you press tab on the black pre-title screen, we could pop up a message that reads "press TAB again to reset gamepad keybindings", or something like that?

**Comment by TerryCavanagh** [comment] 2024-02-13 08:43
On second thoughts, this can wait until 2.5.

**Comment by InfoTeddy** [comment] 2024-02-13 16:00
Closing as a duplicate then. (Fixing this was already planned with the action sets overhaul.)

**Closed by InfoTeddy** 2024-02-13 16:00 UTC
Labels: duplicate
