### ISSUE TITLE
Wrong window size if you unfocus while fullscreened, then re-focus, and then unfullscreen the game

### ISSUE THREAD

**Issue by InfoTeddy** [TerryCavanagh/VVVVVV#387] opened 2020-07-15 19:49 UTC
This bug appears to only happen on Windows. I tested it on my main Linux installation and it didn't happen. But it did happen on my Windows machine. Can't say if it happens on macOS or not.

So, if you have the game in fullscreen, then Alt+Tab out of it, and then Alt+Tab back in, and then unfullscreen the game (via pressing Alt+Enter, Alt+F, F11, or using the option in Graphic Options), then the window size will be incorrect. If you had, say, a window size of 640 by 480 previously, then the new size will be something different.

You get the game into fullscreen in any way possible, it doesn't matter which one. It also doesn't matter the game was started in fullscreen at launch, or if you toggled fullscreen during the session. If you Alt+Tab out and then Alt+Tab back in, your window size will still be correct if you quit the game afterwards, re-launch it, and then unfullscreen the game, so it only gives the wrong window size once you unfullscreen *after* an Alt+Tab.

**Comment by flibitijibibo** [comment] 2020-07-15 19:52
My guess is it's getting a `RESIZED` event - a possible fix would be to check `Game.fullscreen` for window events, and skip calling `Resize()` when the game is in fullscreen (even if it's technically windowed due to alt-tab behavior).

**Comment by NicholeMattera** [comment] 2020-08-13 12:51
Was able to test this on macOS, and wasn't able to reproduce it. Seems to be a Windows only issue.

**Comment by InfoTeddy** [comment] 2020-08-15 02:43
@flibitijibibo I did what you suggested, and unless I misinterpreted or did it wrong, it doesn't seem to fix the bug. See InfoTeddy/VVVVVV@e0d7a2ae38b46d03b34b22849bf2e928a5531abc, InfoTeddy/VVVVVV@bea4544281fe51f7a0a5fda27baf6edc6b15c8be, and InfoTeddy/VVVVVV@10dd0153dcafda2fa3c68c9be2bbb20f6278c483.

**Comment by flibitijibibo** [comment] 2020-08-15 03:05
That's not good... the bug is that Windows is insisting that a user resize happened when toggling fullscreen/windowed, and there's no good way to detect whether or not this is actually true. I would expect macOS and most X/Wayland environments to cooperate, I don't know if Windows will cooperate without even more manual intervention than you've already done. I don't even think FNA has a solution for this, but I don't suppose I've gotten a report for it either so I'd have to check.

**Comment by flibitijibibo** [comment] 2020-10-15 20:49
Going to self-assign this. I was looking at similar annoyances for Streets of Rage 4 (which has a resizable window) and I think I can backport some of the FNA changes to VVVVVV's event loop and window management functionality. This probably won't happen until like... December, but it should be straightforward to write and test if you're familiar with SDL2_FNAPlatform and really want to beat me to this.

**Comment by flibitijibibo** [comment] 2021-02-15 03:53
@InfoTeddy Does this resolve the issue?

https://github.com/TerryCavanagh/VVVVVV/commit/47df6c9d66c492318c8102bde50cd3530ffb22ce

If not we just need to add another flag check for fullscreen to ignore resizes in desktop mode (which we will know the size for anyway). This is just a backport from resize behavior I found while working on Streets of Rage, so it _should_ work, I think...

**Comment by AllyTally** [comment] 2021-02-15 04:50
Doesn't seem resolved...

**Comment by flibitijibibo** [comment] 2021-02-15 05:07
Cool, it just needs a fullscreen check then. That can be written and tested by a Windows dev pretty easily, if anyone's around to try it.

**Comment by InfoTeddy** [comment] 2021-02-15 07:57
I tried doing

```c++
/* Window Resize */
case SDL_WINDOWEVENT_RESIZED:
{
	Uint32 flags = SDL_GetWindowFlags(
		SDL_GetWindowFromID(evt.window.windowID)
	);
	if ((flags & SDL_WINDOW_INPUT_FOCUS)
	&& (flags & SDL_WINDOW_FULLSCREEN))
	{
		resetWindow = true;
	}
	break;
}
```

and

```c++
/* Window Resize */
case SDL_WINDOWEVENT_RESIZED:
{
	Uint32 flags = SDL_GetWindowFlags(
		SDL_GetWindowFromID(evt.window.windowID)
	);
	if ((flags & SDL_WINDOW_INPUT_FOCUS)
	&& (~flags & SDL_WINDOW_FULLSCREEN))
	{
		resetWindow = true;
	}
	break;
}
```

(the difference between the two is one tilde, by the way)

Unless I'm doing something wrong, neither of these two work.

**Comment by flibitijibibo** [comment] 2021-02-15 14:33
Try using the game's fullscreen bool; because we jump out of fullscreen on focus loss that won't be set when we alt-tab back in.

**Comment by InfoTeddy** [comment] 2021-02-15 20:51
Okay, so I tried doing

```c++
case SDL_WINDOWEVENT_RESIZED:
	if ((SDL_GetWindowFlags(
		SDL_GetWindowFromID(evt.window.windowID)
	) & SDL_WINDOW_INPUT_FOCUS)
	&& graphics.screenbuffer->isWindowed)
	{
		resetWindow = true;
	}
	break;
```

and

```c++
case SDL_WINDOWEVENT_RESIZED:
	if ((SDL_GetWindowFlags(
		SDL_GetWindowFromID(evt.window.windowID)
	) & SDL_WINDOW_INPUT_FOCUS)
	&& !graphics.screenbuffer->isWindowed)
	{
		resetWindow = true;
	}
	break;
```

(the difference between the two is one exclamation point)

And it still doesn't work.

**Comment by flibitijibibo** [comment] 2021-02-15 21:16
I would check the section where we assign the window sizes in our settings - a breakpoint will be enough to see where the incorrect values are getting set.

**Comment by InfoTeddy** [comment] 2021-02-15 21:22
So that would be `Screen::ResizeScreen()`, right?

I don't know exactly how to debug on Windows; I'll have to figure that out.

**Comment by flibitijibibo** [comment] 2021-02-15 21:36
Hm, do we have any Visual Studio users in the room? I won't be on Windows for probably another week...

**Comment by flibitijibibo** [comment] 2021-02-16 13:53
I made a quick build and threw it on flibitWindows and cannot reproduce the issue. This is on a plain Windows 7 environment. Pretty much anything I do to the window, no matter how obtuse or unreasonable, it seems to conform to the expected window size really well. Either this is a Windows 10 regression, which is out of my reach, or there's something installed on the PC that affects window size messages, which is a bug in someone else's stuff (typically an overlay program). Either way I've done pretty much all I can do here... a Windows 10 developer will have to take over from here.

**Comment by flibitijibibo** [comment] 2021-04-05 15:13
On top of it apparently not being reproducible anymore, I've opted to start reducing the presence of the focus fullscreen toggle which might have been the cause to begin with:

https://github.com/TerryCavanagh/VVVVVV/commit/5060b4dfe396d7832f579eeef6d0d538ce830ccd

The original patch is from 2013 and I can't make it happen on any of my setups anymore, so I'm going to assume this is limited to some X desktops in 2021 and that's it.

**Closed** 2021-04-05 15:13 UTC
