### ISSUE TITLE
Compilation on Mac

### ISSUE THREAD

**Issue by Innoviox** [TerryCavanagh/VVVVVV#80] opened 2020-01-14 14:52 UTC
To compile on Mac, I had to do the following steps:

1. Download [SDL_mixer.h](https://www.libsdl.org/projects/SDL_mixer/release/SDL_mixer-1.0.6/SDL_mixer.h) and put it in `desktop_version/src`.
2. Run
 ```
$ brew install sdl2 sdl2_image sdl2_mixer
$ export LIBRARY_PATH="$LIBRARY_PATH:/usr/local/lib"
```
3. Change line 18 of `desktop_version/src/SoundSystem.cpp` to 
```c
m_music = (Mix_Music *)Mix_LoadWAV_RW(rw, 0);
```

Hope this is helpful.

**Comment by flibitijibibo** [comment] 2020-01-14 14:55
3 is not a legitimate fix and would almost certainly cause issues in the program, if not an outright crash.

The rest is a duplicate of #41.

**Closed by flibitijibibo** 2020-01-14 14:55 UTC

**Comment by Innoviox** [comment] 2020-01-14 15:04
Without doing it I get this error:
```
desktop_version/src/SoundSystem.cpp:18:12: error: 
      use of undeclared identifier 'Mix_LoadMUS_RW'; did you mean
      'Mix_LoadWAV_RW'?
        m_music = Mix_LoadMUS_RW(rw, 0);
                  ^~~~~~~~~~~~~~
                  Mix_LoadWAV_RW
desktop_version/src/SDL_mixer.h:84:28: note: 
      'Mix_LoadWAV_RW' declared here
extern DECLSPEC Mix_Chunk *Mix_LoadWAV_RW(SDL_RWops *src, int freesrc);
                           ^
desktop_version/src/SoundSystem.cpp:18:12: error: 
      assigning to 'Mix_Music *' (aka '_Mix_Music *') from incompatible type
      'Mix_Chunk *'
        m_music = Mix_LoadMUS_RW(rw, 0);
                  ^~~~~~~~~~~~~~~~~~~~~
2 errors generated.
```

Is this because I am missing a library?

**Comment by flibitijibibo** [comment] 2020-01-14 15:15
Your SDL_mixer version is extremely old - I don't know if this is brew or not, can you compile the SDL libraries from source instead?

**Comment by JackyCZJ** [comment] 2020-01-16 08:43
http://hg.libsdl.org/SDL_mixer/file/cab8eaca3eac/SDL_mixer.h use this version it could help
