### ISSUE TITLE
Booting game with non-English keyboard layout can make some keys unusable / dead keys do not work

### ISSUE THREAD

**Issue by Fussmatte** [TerryCavanagh/VVVVVV#590] opened 2021-01-11 01:53 UTC
If the game is started while a keyboard layout is active that has foreign letters in place of letter keys that the game uses for certain functions (eg Ĉ replacing X, or Ў replacing W) then those functions will not work, even if the keyboard layout is changed back to English. Text input (eg in roomnames, script editor) will always use the current keyboard layout, however.

For example, if I start the game while Esperanto keyboard layout is active, I cannot use the 5×5 brush in the level editor (as X is replaced by Ĉ in that layout) even if I switch back to an English keyboard layout.

The workaround for this issue is to always launch the game with an English layout active.

Additionally, if a keyboard layout is active that has dead keys (ie, keys that produce different letters if a modifier key like AltGr is held down), the dead keys will not work in text input. For example, holding AltGr while pressing the Ĉ key on Linux's Esperanto keyboard layout will produce an X normally, but this does not work in the game.

These issues have only been tested on the Linux version of the game, but I can try to test on Windows as well if it is necessary.

**Comment by flibitijibibo** [comment] 2021-01-11 02:07
We may have to use scancodes until the input system is redone - I don't think we ever really supported non-querty properly aside from a really thin layer for key enums.

**Comment by InfoTeddy** [comment] 2021-01-11 02:10
Yeah, all we've ever done since 2.0 is rely on what SDL gives us, and that's basically pretty much it. We don't have any code that does anything with keyboard layout whatsoever.

**Comment by InfoTeddy** [comment] 2021-01-11 02:15
Fwiw this exact same thing probably happens with Ved (Dav's external VVVVVV custom level editor) too - it uses LÖVE, which uses SDL, and it doesn't have any specific keyboard handling code of its own, either.

**Comment by flibitijibibo** [comment] 2021-01-11 05:38
The issue is pretty common and has to do with scancode translation - this is something SDL provides via SDL_GetKeyFromScancode, and os something I expose in my other work...

https://github.com/FNA-XNA/FNA/wiki/5:-FNA-Extensions#getkeyfromscancodeext

This probably won't get fixed in 2.3, but 2.4 definitely should incorporate this into the input cleanup.

**Comment by flibitijibibo** [comment] 2022-01-18 18:26
Redirecting this to #834...

**Closed by flibitijibibo** 2022-01-18 18:26 UTC
Labels: required for 2.4, localization
