### ISSUE TITLE
Music regressions

### ISSUE THREAD

**Issue by InfoTeddy** [TerryCavanagh/VVVVVV#764] opened 2021-05-17 20:12 UTC
I did some testing, and the new music system in 2.3 still has some kinks...

- [ ] The music played when starting a mode doesn't fade in.
- [ ] If you quit to the menu while a track is fading it, it instantly stops instead of fading out.

**Comment by peripatetes** [comment] 2021-05-20 15:04
The latest Steam build plays Piercing the Sky rather than Positive Force during the final level time trial after DIY V Repair. This wasn't the case with previous builds.

**Comment by flibitijibibo** [comment] 2021-05-20 15:05
> The latest Steam build plays Piercing the Sky rather than Positive Force during the final level time trial after DIY V Repair. This wasn't the case with previous builds.

This was intentional, see #763

**Comment by peripatetes** [comment] 2021-05-20 22:56
Ok then, doesn't fall into this category. Doesn't seem like an improvement to me; I added a comment on #763 .

**Comment by flibitijibibo** [comment] 2021-06-14 18:59
Identified the cause of the music fade in problem, working on this now. May also accidentally fix the fade out problem as well.

**Comment by flibitijibibo** [comment] 2021-06-14 19:13
Fixed via https://github.com/TerryCavanagh/VVVVVV/commit/85205332969b03a0182c3f2aad2687195d18b840 and https://github.com/TerryCavanagh/VVVVVV/commit/43e8d31aa9be31957d502d30c9da4cf105b0982e. Rebuilding the Steam beta now.

**Closed** 2021-06-14 19:12 UTC
Labels: required for 2.3
