### ISSUE TITLE
Focusing another window during time trial countdown, then waiting causes audio bug

### ISSUE THREAD

**Issue by tzann** [TerryCavanagh/VVVVVV#699] opened 2021-04-05 23:55 UTC
Steps to reproduce:
1. Start any time trial
2. Focus another window during the start of the countdown (make sure Unfocus Pause is turned on)
3. Wait long enough for the Par Time of the level to run out
4. Focus the game
This causes the game to repeatedly play the "sad" sound effect until the time trial starts.

**Comment by InfoTeddy** [comment] 2021-04-06 01:02
Yeah, I noticed that the game timer still ticks during unfocus pause. I think the right thing to do is to make sure it doesn't tick during unfocus pause...

**Comment by tzann** [comment] 2021-04-06 01:06
Wouldn't it make more sense to pause it during the countdown to time trials?

Pausing the game timer during unfocus pause could lead to very weird speedrunning strats, given we use the in-game timer for almost everything.

**Comment by InfoTeddy** [comment] 2021-04-06 01:11
The game doesn't update at all during unfocus pause, so I don't see how that could lead to any strats. The only thing that updates is the fadebars, which isn't very useful (and should probably be fixed too).

On an unrelated note, it looks like the timer after the countdown gets reset during a drawing function, which I didn't notice and is pretty yikes... that should be fixed too.

**Comment by flibitijibibo** [comment] 2021-04-06 02:20
Is this a carryover from 2.2, or is it unique to 2.3?

**Comment by InfoTeddy** [comment] 2021-04-06 02:21
I haven't tested it, but I'm pretty certain there's no way 2.3 could have introduced this. The lines of code involved are ones I have basically never touched.

**Comment by flibitijibibo** [comment] 2021-04-06 02:47
That's what I figured - as long as this isn't a regression we can mark this for 2.4.

**Comment by tzann** [comment] 2021-04-06 03:02
Yeah it's also present in 2.2, that's where I actually found it - then I just tested 2.3 to see if it was still the same.

**Comment by tzann** [comment] 2021-04-06 04:00
> The game doesn't update at all during unfocus pause, so I don't see how that could lead to any strats.
I more meant in the sense that you might be able to pause buffer inputs without sacrificing the time that elapses during the pause. For unfocus pause, I don't think it matters too much, but it would certainly matter if a normal pause also paused the game timer.

**Comment by InfoTeddy** [comment] 2021-04-06 04:31
You can't pause buffer inputs during the unfocus pause. The recognition that a keypress was released only happens in the relevant loop input functions (e.g. `gameinput()`). You also can't pause buffer inputs using the normal pause (I tried it with libTAS).

**Comment by tzann** [comment] 2021-04-06 12:22
You _can_ pause buffer directional inputs using the normal pause.

**Comment by InfoTeddy** [comment] 2021-04-06 16:36
Oh, yeah, you can. Although it doesn't let you do anything that would be impossible without pause buffering otherwise. Regardless, I'll probably make the timer not tick during unfocus pause, and also make it not tick during the countdown.

**Closed** 2021-04-13 21:51 UTC
Labels: required for 2.4
