### ISSUE TITLE
Consider GPL for the license?

### ISSUE THREAD

**Issue by Cpt-Derp** [TerryCavanagh/VVVVVV#13] opened 2020-01-10 22:05 UTC
It's your game, your code, and I'm sure a lot of us are happy that the source code of this great game can be studied and tinkered with. However, following the example of John Carmack (id Tech 1 - 4 and Quake engines) and releasing the source code under the GPL license would provide several advantages to the community with no practical disadvantages to you (that I'm aware of anyway):

- Under the GPL, FOSS projects such as Debian have liberty to include the engine in its official repository.

- It effectively becomes a part of a large community of dedicated programmers, and with the legal clarity that the GPL provides, it would foster a healthier community of modders around the engine/game, and may serve as a base for new games.

- Commercial use, in principle, is not directly allowed, only support for the software may be sold, or something alongside the compiled source code (in this case, the proprietary game assets). Everyone who distributes a binary of the engine must also release the source code, even if there's a price tag.

- You can still dual license. For example, id software allows any developer with enough green to negotiate special proprietary licensing to use their engines, although they encourage you to just stick with the GPL.

For the benefit of the community, I hope you will consider this proposal :slightly_smiling_face:

**Comment by flibitijibibo** [comment] 2020-01-10 22:19
Duplicate of #7, but the TL;DR is that we probably won't do it.

**Closed by flibitijibibo** 2020-01-10 22:19 UTC
