### ISSUE TITLE
Complete tarball (with submodules) for v2.4.2?

### ISSUE THREAD

**Issue by i0ntempest** [TerryCavanagh/VVVVVV#1190] opened 2024-08-24 06:41 UTC
I've waited for a few days but a complete tarball is still not uploaded yet. @flibitijibibo could you please make one?
Also I still think configuring a workflow for this would be better, it'll save you the hassle of doing this for every release.

**Comment by InfoTeddy** [comment] 2024-08-24 11:06
Duplicate of #1189.

**Closed** 2024-08-24 11:06 UTC
